import { Outfit, Brand, Garment, Profile } from '../types'

export const mockBrands: Brand[] = [
  { id: '1', name: 'Zara', logo_url: null, verified: true, created_at: '' },
  { id: '2', name: 'Mango', logo_url: null, verified: true, created_at: '' },
  { id: '3', name: 'Pull&Bear', logo_url: null, verified: false, created_at: '' },
  { id: '4', name: 'H&M', logo_url: null, verified: true, created_at: '' },
  { id: '5', name: 'Stradivarius', logo_url: null, verified: false, created_at: '' },
]

export const mockProfile: Profile = {
  id: 'user-1',
  username: '@sofialopez',
  full_name: 'Sofía López',
  bio: 'Amante del street style y la moda sostenible ✨',
  avatar_url: 'https://i.pravatar.cc/150?img=47',
  style_tags: ['natural', 'oversize', 'streetwear'],
  followers_count: 2840,
  following_count: 312,
  outfits_count: 48,
  created_at: '',
}

export const mockGarments: Garment[] = [
  {
    id: 'g1', brand_id: '1', name: 'Blazer oversize', price: 49.99,
    slot: 'torso', image_url: 'https://picsum.photos/seed/g1/200/250',
    colors: ['beige'], sizes: ['XS', 'S', 'M', 'L'], style_tags: ['oversize'], created_at: '',
  },
  {
    id: 'g2', brand_id: '2', name: 'Wide leg jeans', price: 39.99,
    slot: 'piernas', image_url: 'https://picsum.photos/seed/g2/200/250',
    colors: ['azul', 'negro'], sizes: ['34', '36', '38', '40'], style_tags: ['natural'], created_at: '',
  },
  {
    id: 'g3', brand_id: '3', name: 'Chunky sneakers', price: 59.99,
    slot: 'calzado', image_url: 'https://picsum.photos/seed/g3/200/250',
    colors: ['blanco'], sizes: ['36', '37', '38', '39', '40'], style_tags: ['streetwear'], created_at: '',
  },
  {
    id: 'g4', brand_id: '1', name: 'Crop top ribbed', price: 17.99,
    slot: 'torso', image_url: 'https://picsum.photos/seed/g4/200/250',
    colors: ['blanco', 'negro', 'beige'], sizes: ['XS', 'S', 'M'], style_tags: ['natural'], created_at: '',
  },
  {
    id: 'g5', brand_id: '4', name: 'Mini falda plisada', price: 29.99,
    slot: 'piernas', image_url: 'https://picsum.photos/seed/g5/200/250',
    colors: ['negro', 'marrón'], sizes: ['XS', 'S', 'M', 'L'], style_tags: ['urban'], created_at: '',
  },
]

export const mockOutfits: Outfit[] = [
  {
    id: 'o1',
    creator_id: 'user-1',
    brand_id: '1',
    title: 'Look casual chic',
    description: 'El outfit perfecto para el día a día con estilo',
    image_url: 'https://picsum.photos/seed/outfit1/400/700',
    total_price: 127.97,
    discount_percent: 15,
    occasion: ['salir', 'estudiar'],
    style_tags: ['casual', 'chic'],
    likes_count: 342,
    saves_count: 89,
    published_at: new Date().toISOString(),
    brand: mockBrands[0],
    creator: mockProfile,
    garments: [
      { outfit_id: 'o1', garment_id: 'g1', position_x: 0.3, position_y: 0.3, garment: mockGarments[0] },
      { outfit_id: 'o1', garment_id: 'g2', position_x: 0.6, position_y: 0.6, garment: mockGarments[1] },
    ],
  },
  {
    id: 'o2',
    creator_id: 'user-1',
    brand_id: '2',
    title: 'Street style vibes',
    description: 'Urban look para destacar en la ciudad',
    image_url: 'https://picsum.photos/seed/outfit2/400/700',
    total_price: 109.97,
    discount_percent: 0,
    occasion: ['salir'],
    style_tags: ['streetwear', 'urban'],
    likes_count: 521,
    saves_count: 134,
    published_at: new Date().toISOString(),
    brand: mockBrands[1],
    creator: mockProfile,
    garments: [
      { outfit_id: 'o2', garment_id: 'g4', position_x: 0.4, position_y: 0.25, garment: mockGarments[3] },
      { outfit_id: 'o2', garment_id: 'g5', position_x: 0.5, position_y: 0.6, garment: mockGarments[4] },
      { outfit_id: 'o2', garment_id: 'g3', position_x: 0.35, position_y: 0.85, garment: mockGarments[2] },
    ],
  },
  {
    id: 'o3',
    creator_id: 'user-1',
    brand_id: '3',
    title: 'Minimal & clean',
    description: 'Menos es más. Tonos neutros que nunca fallan.',
    image_url: 'https://picsum.photos/seed/outfit3/400/700',
    total_price: 147.97,
    discount_percent: 10,
    occasion: ['estudiar', 'salir'],
    style_tags: ['minimal', 'natural'],
    likes_count: 198,
    saves_count: 67,
    published_at: new Date().toISOString(),
    brand: mockBrands[2],
    creator: mockProfile,
    garments: [
      { outfit_id: 'o3', garment_id: 'g1', position_x: 0.45, position_y: 0.3, garment: mockGarments[0] },
      { outfit_id: 'o3', garment_id: 'g2', position_x: 0.55, position_y: 0.65, garment: mockGarments[1] },
    ],
  },
  {
    id: 'o4',
    creator_id: 'user-1',
    brand_id: '4',
    title: 'Night out look',
    description: 'Para esas noches que quieres brillar.',
    image_url: 'https://picsum.photos/seed/outfit4/400/700',
    total_price: 89.97,
    discount_percent: 20,
    occasion: ['fiesta'],
    style_tags: ['elegante', 'noche'],
    likes_count: 876,
    saves_count: 243,
    published_at: new Date().toISOString(),
    brand: mockBrands[3],
    creator: mockProfile,
    garments: [],
  },
  {
    id: 'o5',
    creator_id: 'user-1',
    brand_id: '5',
    title: 'Cozy weekend',
    description: 'Cómoda sin perder el estilo el fin de semana.',
    image_url: 'https://picsum.photos/seed/outfit5/400/700',
    total_price: 79.97,
    discount_percent: 0,
    occasion: ['estudiar'],
    style_tags: ['cozy', 'casual'],
    likes_count: 415,
    saves_count: 98,
    published_at: new Date().toISOString(),
    brand: mockBrands[4],
    creator: mockProfile,
    garments: [],
  },
]
